apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::043134281602:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::043134281602:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-SX2PI45W9V5P
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-03-08T23:00:07Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "965"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: "8e5a89ff-6190-11ea-a469-0eeec8652acb"
